config/routes.rb
Rails.application.routes.draw do

  root 'home#top'

  resources :posts

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    agent = Mechanize.new
    page = agent.get("https://www.apple.com/jp")
    @links = page.search("a")

  end

  def show
    
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>スクレイピングのためのアプリだよ</p>

<%= link_to "ここをクリック", posts_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scraping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>スクレイピング結果を表示中</p>


<% @links.each do |link| %>
<p><%= link_to link.text, "https://www.apple.com/#{link.get_attribute('href') }" %></p>
<% end %>




<%= link_to "ホーム画面へ", root_path %>